spring:

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        max-page-size: 100

  jpa:
    hibernate:
      # 使用 Flyway 管理数据库版本，关闭 Hibernate 自动建表
      # ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
     # use-new-id-generator-mappings: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        new-generator-mappings: false
        format-sql: true
        show-sql: true
        use-sql-comments: true

#  datasource:
#    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:boot}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#    username: ${DB_USER:root}
#    password: ${DB_PWD:mysql8}

  datasource:
    url: jdbc:sqlite:./data-jpa/db/jpa.db
    driver-class-name: org.sqlite.JDBC
    # url: jdbc:h2:./data-jpa/db/jpa.db;NON_KEYWORDS=USER
    # username: sa
    # driverClassName: org.h2.Driver

    hikari:
    # 连接数 = ((cpu核数 * 2) + 磁盘有效主轴数)
      maximum-pool-size: 10
      minimum-idle: 10
      # 官方推荐 MYSQL驱动的配置参数
      data-source-properties:
        cachePrepStmts: true
        # 开启服务端预编译
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

  flyway:
    enabled: true
    table: flyway_schema_history
    locations:
      - classpath:db/migration
    # ★ SQLite 不支持跨脚本事务，建议关闭整个迁移的事务包裹
    mixed: true

    # 基线配置
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"

    clean-disabled: true
    # ★ SQLite 不支持某些默认的锁策略，建议关掉校验重试
    retry-failures: false

    callback-locations:
      - classpath:db/callback

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace